// Mock Data for AI for Data Engineering
// Roles: Data Engineer, Data Architect

export const dataEngineeringMockData = {
  "Data Engineer": {
    topbar: {
      title: "AI for Data Engineering · Pipeline & Streaming Operations Desk",
      subtitle: "ETL/ELT Orchestration, Data Observability, Schema Migration & Streaming Telemetry",
      platform: "DATA-ENG",
      shift: "Batch & Streaming Shift | Real-Time Sync · Active",
      shiftProgress: "56%",
      statusBadge: "● DATA PIPELINE MESH · LIVE",
    },
    summary: {
      greeting: "Good morning, Data Engineer",
      subtext: "42 active DAGs · 1.8B events processed today · 99.98% pipeline freshness SLA",
      chips: [
        { label: "PIPELINE SLA", value: "99.98%", color: "var(--cyan)" },
        { label: "THROUGHPUT", value: "142k msg/s", color: "#50c878" },
        { label: "DATA QUALITY PASS", value: "99.2%", color: "#50c878" },
        { label: "SCHEMA INTEGRITY", value: "100%", color: "var(--cyan)" },
      ],
    },
    tabs: [
      { id: "overview", label: "Overview", active: true },
      { id: "pipelines", label: "ETL Pipelines", badge: 4 },
      { id: "data_quality", label: "Data Quality & Drift", badge: 3 },
      { id: "streaming", label: "Kafka & Streaming", badge: 3 },
    ],
    stateOfEnvironment: {
      title: "Data Pipelines & Warehouse Ingestion Health",
      tag: "Airflow, Spark & Snowflake Mesh",
      metrics: [
        { id: "m1", count: 1, label: "Failed DAG", color: "red" },
        { id: "m2", count: 14, label: "Running DAGs", color: "blue" },
        { id: "m3", count: 38, label: "Succeeded DAGs", color: "green" },
        { id: "m4", count: 142, label: "Total Tables", color: "gray" },
      ],
      items: [
        {
          id: "e1",
          title: "telemetry-raw-events-ingest (Kafka -> Iceberg)",
          status: "Healthy",
          statusType: "good",
          desc: "142k events/sec · P95 latency 210ms · Zero consumer lag on primary partitions",
        },
        {
          id: "e2",
          title: "daily-vehicle-telematics-dbt (Snowflake Warehouse)",
          status: "Warning",
          statusType: "warn",
          desc: "Warehouse auto-resumed for 42 minutes · 1 dbt test warning on null vin_identifier constraint",
        },
        {
          id: "e3",
          title: "vehicle-fleet-360-cdc-sync (Debezium -> Spark Lakehouse)",
          status: "Schema Drift",
          statusType: "danger",
          desc: "Source table added column `ecu_firmware_version` without target schema evolution mapping",
        },
      ],
    },
    whatRequiresAttention: {
      title: "Data Pipeline & Quality Alerts",
      tag: "3 Engineering Items",
      cards: [
        {
          id: "a1",
          title: "P1 · Partition Skew on vehicle-telematics-stream Topic",
          severity: "Act now",
          severityType: "critical",
          desc: "Partition 4 lag is 12x higher than average due to hotspot key hashing",
          progress: 92,
        },
        {
          id: "a2",
          title: "P2 · Schema Evolution Needed on customer_orders",
          severity: "Review",
          severityType: "review",
          desc: "Automated schema migration PR generated by Data Engineering Copilot",
          progress: 75,
        },
        {
          id: "a3",
          title: "P3 · S3 Parquet Compaction Job Delayed",
          severity: "At risk",
          severityType: "critical",
          desc: "Small file problem accumulating in raw landing zone — 14,000 files awaiting merge",
          progress: 50,
        },
      ],
    },
    criticalRisks: {
      title: "Pipeline SLA & Warehouse Governance",
      tag: "Data SLA Watch",
      cards: [
        {
          id: "r1",
          title: "Fleet Telematics Freshness SLA Breached in 18 Minutes",
          severity: "High",
          severityType: "high",
          desc: "Batch transform blocked by lock contention on vehicle dimension lookup table",
        },
        {
          id: "r2",
          title: "Snowflake Warehouse Compute Credit Consumption Spike",
          severity: "Elevated",
          severityType: "warn",
          desc: "Unoptimized cartesian join detected in ad-hoc query submitted from BI reporting tool",
        },
        {
          id: "r3",
          title: "Consumer Group Lag Creep on High-Priority Safety Stream",
          severity: "Elevated",
          severityType: "warn",
          desc: "ADAS event consumer group lagging behind real-time offset by 8,500 messages",
        },
      ],
    },
    tabData: {
      pipelines: {
        title: "ETL / ELT Pipeline Execution Telemetry",
        sub: "Orchestration runs across Apache Airflow, dbt Cloud and AWS Glue",
        items: [
          { id: "dag1", code: "DAG-INGEST-01", name: "telemetry_realtime_ingest", status: "Running", statusType: "good", desc: "Real-time streaming ingestion from Kafka into Apache Iceberg table format", duration: "Continuous", checks: "142k msg/s", target: "Spark Streaming" },
          { id: "dag2", code: "DAG-DBT-02", name: "dbt_financial_reconciliation", status: "Succeeded", statusType: "good", desc: "Daily financial ledger rollups with automated reconciliation assertions", duration: "18m 34s", checks: "48/48 Passed", target: "Snowflake XL" },
          { id: "dag3", code: "DAG-CDC-03", name: "cdc_customer_orders_sync", status: "Failed", statusType: "danger", desc: "PostgreSQL WAL decoder error due to unsupported schema change event", duration: "Failed at 04:12", checks: "Schema Error", target: "Debezium / SQS" },
          { id: "dag4", code: "DAG-ML-04", name: "feature_store_enrichment", status: "Succeeded", statusType: "good", desc: "Feature generation and online Feast store sync for predictive AI models", duration: "32m 10s", checks: "100% Fresh", target: "Ray / Databricks" },
        ],
      },
      data_quality: {
        title: "Data Quality Observability & Schema Drift",
        sub: "Great Expectations validation, distribution anomalies & schema evolution",
        items: [
          { id: "dq1", code: "RULE-UNQ-01", name: "Unique Identifier Integrity", status: "Passed", statusType: "good", desc: "Verified 12.4M records in dim_vehicles — zero duplicate primary keys detected", metric: "Duplicate Rate: 0.00%", target: "< 0.01%" },
          { id: "dq2", code: "RULE-NLL-02", name: "Non-Null Mandatory Columns", status: "Warning", statusType: "warn", desc: "Detected 14 null values in mandatory postal_code field on newly ingested records", metric: "Null Rate: 0.0012%", target: "0.00%" },
          { id: "dq3", code: "RULE-DRIFT-03", name: "Schema Evolution Drift Detection", status: "Action Needed", statusType: "danger", desc: "Incoming JSON payload contains unexpected nested object `geo_coordinates`", metric: "Schema Compatibility: Breaking", target: "Full Backwards Compatible" },
        ],
      },
      streaming: {
        title: "Kafka & Streaming Infrastructure Health",
        sub: "Message brokers, consumer group offsets, partition throughput & lag monitor",
        items: [
          { id: "st1", code: "TOPIC-01", name: "vehicle-telematics-stream", status: "Active", statusType: "good", desc: "High-frequency IoT sensor packets from connected vehicle fleet", checks: "88,000 msg/sec", target: "Lag: 420ms", duration: "Retention 7d" },
          { id: "st2", code: "TOPIC-02", name: "dealer-inventory-events", status: "Active", statusType: "good", desc: "Real-time dealer vehicle inventory changes and trade allocations", checks: "4,200 msg/sec", target: "Lag: 80ms", duration: "Retention 30d" },
          { id: "st3", code: "TOPIC-03", name: "customer-diagnostic-alerts", status: "Lag Warning", statusType: "warn", desc: "Onboard diagnostic trouble codes (DTC) prioritized alert stream", checks: "12,500 msg/sec", target: "Lag: 3,800ms", duration: "Retention 14d" },
        ],
      },
    },
  },

  "Data Architect": {
    topbar: {
      title: "AI for Data Engineering · Data Architecture & Governance Portal",
      subtitle: "Enterprise Lakehouse Architecture, Data Modeling & Regulatory Compliance",
      platform: "DATA-ARCH",
      shift: "Enterprise Architecture Review | Q3 Roadmap",
      shiftProgress: "50%",
      statusBadge: "● DATA ARCH MESH · LIVE",
    },
    summary: {
      greeting: "Good morning, Data Architect",
      subtext: "14 data domains modeled · 100% schema registry compliance · Lakehouse storage optimized",
      chips: [
        { label: "DATA QUALITY SCORE", value: "99.4%", color: "var(--cyan)" },
        { label: "SCHEMA REGISTRY", value: "100% OK", color: "#50c878" },
        { label: "STORAGE SAVINGS", value: "$14k/mo", color: "#50c878" },
        { label: "LINEAGE COVERAGE", value: "96.8%", color: "var(--cyan)" },
      ],
    },
    tabs: [
      { id: "overview", label: "Overview", active: true },
      { id: "data_models", label: "Data Models & Schemas", badge: 8 },
      { id: "agentic_execution", label: "Agentic Execution" },
      { id: "governance", label: "Governance & Lineage", badge: 4 },
      { id: "cost_analytics", label: "Compute & Cost", badge: 3 },
    ],
    stateOfEnvironment: {
      title: "Enterprise Lakehouse Domain Health",
      tag: "Data Mesh & Governance",
      metrics: [
        { id: "m1", count: 0, label: "Compliance Breaches", color: "green" },
        { id: "m2", count: 4, label: "Under Review", color: "orange" },
        { id: "m3", count: 14, label: "Certified Domains", color: "blue" },
        { id: "m4", count: 280, label: "Active Pipelines", color: "gray" },
      ],
      items: [
        {
          id: "e1",
          title: "Customer 360 Profile Database (Gold Layer)",
          status: "Certified",
          statusType: "good",
          desc: "Certified central database linking customer profiles, car ownership, and service history with privacy protection",
        },
        {
          id: "e2",
          title: "Supply Chain & Parts Inventory Model (Silver Layer)",
          status: "Under Review",
          statusType: "warn",
          desc: "Cleaned real-time parts inventory tracking across 1,200 regional dealership hubs",
        },
      ],
    },
    whatRequiresAttention: {
      title: "Architecture Review & Approvals",
      tag: "3 Review Items",
      cards: [
        {
          id: "a1",
          title: "P1 · Customer Privacy & PII Data Encryption",
          severity: "Review",
          severityType: "review",
          desc: "Verify automated encryption keys on newly added customer profile attributes before production release",
          progress: 85,
        },
        {
          id: "a2",
          title: "P2 · US & Europe Cross-Region Data Sync",
          severity: "Action Needed",
          severityType: "critical",
          desc: "Speed up cross-cloud database synchronization between US and Europe regional data centers",
          progress: 92,
        },
        {
          id: "a3",
          title: "P3 · New EV Battery Sensor Data Format Approval",
          severity: "Review",
          severityType: "review",
          desc: "Approve schema update for incoming electric vehicle battery health telemetry",
          progress: 68,
        },
      ],
    },
    criticalRisks: {
      title: "Architecture & SLA Blockers",
      tag: "3 Lakehouse Risks",
      cards: [
        {
          id: "r1",
          title: "Cold Data Archiving Needed for Old Car Sensor Data",
          severity: "Elevated",
          severityType: "warn",
          desc: "Move car sensor data older than 90 days to cheap long-term cloud storage to save $14,000/month",
        },
        {
          id: "r2",
          title: "Raw Data Exceeding 30-Day Retention Limit",
          severity: "Critical",
          severityType: "critical",
          desc: "Unprocessed factory sensor logs need automated purging after 30 days to stay compliant with data regulations",
        },
        {
          id: "r3",
          title: "Cloud Compute Budget Approaching 85% Monthly Cap",
          severity: "Elevated",
          severityType: "warn",
          desc: "High query volume on vehicle service history approaching monthly cloud compute budget limit",
        },
      ],
    },
    tabData: {
      data_models: {
        title: "Enterprise Data Models & Schemas",
        sub: "Medallion architecture layers, conceptual entity relationship diagrams and schema definitions",
        items: [
          { id: "dm1", code: "MOD-GOLD-01", name: "Customer 360 Star Schema", status: "Production", statusType: "good", desc: "Gold layer dimensional model connecting accounts, vehicle telematics, and service orders", target: "Iceberg / Snowflake", checks: "100% Certified" },
          { id: "dm2", code: "MOD-SLV-02", name: "Vehicle Telemetry Event Model", status: "Production", statusType: "good", desc: "Silver layer cleaned sensor readings with time-series optimization", target: "Delta Lake / Databricks", checks: "100% Certified" },
        ],
      },
      agentic_execution: {
        title: "Agentic Execution",
        sub: "Autonomous multi-agent execution desk for data pipeline orchestration, schema migrations, and real-time governance actions.",
        items: [],
      },
      governance: {
        title: "Data Lineage & Governance Telemetry",
        sub: "OpenLineage tracking, catalog classification and GDPR/CCPA regulatory tagging",
        items: [
          { id: "gv1", code: "GOV-01", name: "Automated Data Lineage Mapping", status: "Active", statusType: "good", desc: "End-to-end lineage from Kafka ingestion to Tableau executive dashboards", checks: "96.8% Coverage" },
          { id: "gv2", code: "GOV-02", name: "PII Automated Tagging Policy", status: "Enforced", statusType: "good", desc: "Dynamic data masking enabled on credit card and tax identification fields", checks: "100% Enforced" },
        ],
      },
      cost_analytics: {
        title: "Warehouse & Cloud Storage Cost Optimization",
        sub: "Snowflake virtual warehouse utilization, auto-suspend efficiency and query optimization",
        items: [
          { id: "ca1", code: "COST-01", name: "Snowflake Compute Right-Sizing", status: "Optimized", statusType: "good", desc: "Scaled transform cluster down during off-peak hours, saving $8,400/month", metric: "Savings: $8.4k/mo" },
          { id: "ca2", code: "COST-02", name: "Iceberg Compaction Policy", status: "Active", statusType: "good", desc: "Reduced S3 metadata API read operations by 64% using table optimization jobs", metric: "API calls: -64%" },
        ],
      },
    },
  },

  "Data Scientist": {
    topbar: {
      title: "AI for Data Engineering · Data Science & ML Workbench",
      subtitle: "Predictive Modeling, Feature Engineering, Model Drift & ML Inference Telemetry",
      platform: "DATA-SCI",
      shift: "Model Training & Deployment Shift | Active Models · Live",
      shiftProgress: "64%",
      statusBadge: "● ML INFERENCE MESH · LIVE",
    },
    summary: {
      greeting: "Good morning, Data Scientist",
      subtext: "12 active ML models · 99.4% inference accuracy · 4 training runs scheduled today",
      chips: [
        { label: "MODEL ACCURACY", value: "98.7%", color: "var(--cyan)" },
        { label: "FEATURE STORE", value: "240 Feats", color: "#50c878" },
        { label: "INFERENCE P95", value: "18ms", color: "#50c878" },
        { label: "DRIFT DETECTIONS", value: "0 Critical", color: "var(--cyan)" },
      ],
    },
    tabs: [
      { id: "overview", label: "Overview", active: true },
      { id: "ml_models", label: "ML Models & Training", badge: 6 },
      { id: "feature_store", label: "Feature Store", badge: 4 },
      { id: "model_drift", label: "Model Drift & Monitor", badge: 3 },
    ],
    stateOfEnvironment: {
      title: "Production ML Models & Inference Pipelines",
      tag: "MLOps & Feature Store",
      metrics: [
        { id: "m1", count: 0, label: "Model Alerts", color: "green" },
        { id: "m2", count: 4, label: "Training Runs", color: "orange" },
        { id: "m3", count: 12, label: "Deployed Models", color: "blue" },
        { id: "m4", count: 240, label: "Online Features", color: "gray" },
      ],
      items: [
        {
          id: "e1",
          title: "EV Battery Degradation Predictor (XGBoost v2.4)",
          status: "Optimal",
          statusType: "good",
          desc: "Predicts remaining battery health cycle from CAN-bus telemetry · 99.2% R² score",
        },
        {
          id: "e2",
          title: "Predictive Maintenance DTC Classifier (PyTorch v1.8)",
          status: "Training",
          statusType: "warn",
          desc: "Automated retrain scheduled with 500k vehicle telemetry frames from assembly plants",
        },
        {
          id: "e3",
          title: "Dealership Demand & Inventory Forecaster (Prophet v3)",
          status: "Production",
          statusType: "good",
          desc: "Daily time-series forecast for parts replenishment across 1,200 regional hubs",
        },
      ],
    },
    whatRequiresAttention: {
      title: "ML Engineering & Model Health Alerts",
      tag: "3 Items Pending Review",
      cards: [
        {
          id: "a1",
          title: "P1 · Covariate Shift Alert on Powertrain Telematics",
          severity: "Act now",
          severityType: "critical",
          desc: "Winter ambient temperature input distribution deviates 18% from training baseline",
          progress: 85,
        },
        {
          id: "a2",
          title: "P2 · Model Retraining Pipeline Waiting for GPU Cluster",
          severity: "Review",
          severityType: "review",
          desc: "Kubeflow distributed training job queued on A100 GPU nodegroup",
          progress: 60,
        },
        {
          id: "a3",
          title: "P3 · Feature Store Staleness on Speed & Braking Metrics",
          severity: "Monitor",
          severityType: "good",
          desc: "Feast feature store synchronization latency currently at 1.4s",
          progress: 40,
        },
      ],
    },
    criticalRisks: {
      title: "Model Drift & Infrastructure Risks",
      tag: "ML Governance",
      cards: [
        {
          id: "r1",
          title: "Inference Latency Spike on Edge Micro-Service",
          severity: "Critical",
          severityType: "critical",
          desc: "Triton Inference Server p99 reached 85ms on peak connected vehicle telemetry hours",
        },
        {
          id: "r2",
          title: "Data Label Ingestion Latency on Assembly Quality Feed",
          severity: "Elevated",
          severityType: "high",
          desc: "Ground-truth feedback loop delayed by 4 hours during plant shift change",
        },
        {
          id: "r3",
          title: "Feast Feature Store Staleness on Speed & Braking Metrics",
          severity: "High",
          severityType: "high",
          desc: "Online feature store cache hit ratio dropped below 92% on peak fleet telematics hours",
        },
      ],
    },
    tabData: {
      ml_models: {
        title: "Production Machine Learning Models & Training Jobs",
        sub: "Registry of versioned models, training runs, hyperparameter evaluations & deployment endpoints",
        items: [
          { id: "ml1", code: "ML-EV-01", name: "EV Battery Degradation Predictor", status: "Production", statusType: "good", desc: "Gradient boosted trees on CAN bus telemetry for battery life estimation", target: "TorchServe / EKS", progress: 99.2, checks: "AUC: 0.98" },
          { id: "ml2", code: "ML-DTC-02", name: "Powertrain DTC Failure Predictor", status: "Training", statusType: "warn", desc: "Deep transformer model identifying early symptoms of mechanical failure", target: "Vertex AI / TPU", progress: 74.5, checks: "F1: 0.94" },
          { id: "ml3", code: "ML-INV-03", name: "Vehicle Inventory Demand Forecaster", status: "Production", statusType: "good", desc: "Multi-horizon time-series forecasting model for dealer stock replenishment", target: "Snowflake ML", progress: 98.1, checks: "MAPE: 3.2%" },
        ],
      },
      feature_store: {
        title: "Enterprise ML Feature Store (Feast / Hopsworks)",
        sub: "Curated low-latency online and offline feature tables for real-time model inference",
        items: [
          { id: "fs1", code: "FEAT-01", name: "telematics_rolling_avg_rpm_30m", status: "Active", statusType: "good", desc: "Rolling average engine RPM calculated over 30-minute connected windows", metric: "Latency: 2ms", target: "Redis Online Store" },
          { id: "fs2", code: "FEAT-02", name: "battery_temperature_delta_celsius", status: "Active", statusType: "good", desc: "High-precision ambient vs core battery temperature variance", metric: "Latency: 3ms", target: "Redis Online Store" },
          { id: "fs3", code: "FEAT-03", name: "dealer_historical_lead_conversion_rate", status: "Active", statusType: "good", desc: "Aggregated 90-day lead conversion velocity per dealership zipcode", metric: "Latency: 12ms", target: "Snowflake Feature Table" },
        ],
      },
      model_drift: {
        title: "Real-Time Model Drift & Data Quality Observability",
        sub: "Evidently AI & Prometheus monitoring for concept drift, covariate shift & prediction degradation",
        items: [
          { id: "md1", code: "DRIFT-01", name: "Battery Health Predictor Input Drift", status: "No Drift", statusType: "good", desc: "Wasserstein distance < 0.05 across all 28 telemetry input features", checks: "P-Value: 0.88", target: "Green" },
          { id: "md2", code: "DRIFT-02", name: "Powertrain DTC Output Distribution", status: "Minor Shift", statusType: "warn", desc: "Shift detected in DTC-P0300 frequency following recent firmware rollout", checks: "P-Value: 0.04", target: "Watch" },
          { id: "md3", code: "DRIFT-03", name: "Inventory Demand Covariate Shift", status: "Healthy", statusType: "good", desc: "Seasonal economic adjustments normalized against historical trendlines", checks: "P-Value: 0.92", target: "Green" },
        ],
      },
    },
  },
};

// Compatibility alias
dataEngineeringMockData["Data Engineer"] = dataEngineeringMockData["Data Architect"];
